site_name: Pstock
site_description: Async python sdk for stock data, get latest prices, news, events, .. from yahoo-finance, finviz, alpaca, ... with the same api.
site_url: https://obendidi.github.io/pstock

repo_name: obendidi/pstock
repo_url: https://github.com/obendidi/pstock
edit_uri: ""


theme:
  name: "material"
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
- css/style.css

nav:
  - Introduction: "index.md"
  - Schemas: schemas-reference.md
  - Isin: isin-reference.md
  - Yahoo-finance: yahoo-finance-reference.md


plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
