site_name: Pstock
site_description: Async yahoo-finance python api with pydantic models.
site_url: https://obendidi.github.io/pstock

repo_name: obendidi/pstock
repo_url: https://github.com/obendidi/pstock
edit_uri: ""


theme:
  name: "material"
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
- css/style.css

nav:
  - Introduction: "index.md"
  - User Guide: "user-guide.md"
  - API: "api.md"


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
            filters:
              - "!^_"  # exlude all members starting with _
              # - "!^__"  # exlude all members starting with __
              - "^__root__$"  # except for __root__
              - "^__init__$"  # but always include __init__ modules and methods
          rendering:
            heading_level: 3
            members_order: source
            show_if_no_docstring: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            show_source: true
            show_root_members_full_path: true
      watch:
        - pstock

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
