name: Publish Python 🐍 distributions 📦 to PyPI
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-n-publish:
    name: Build and publish Python
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.12
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      #              Build package
      #----------------------------------------------
      - name: Build package
        run: poetry build
      #----------------------------------------------
      #              Publish to Pypi
      #----------------------------------------------
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
